# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-29 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20170329_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='dut_date',
            new_name='due_date',
        ),
    ]
