# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-30 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_tasklist_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(related_name='task', to='todolist.Tag'),
        ),
    ]
