# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 11:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='shared',
            field=models.ManyToManyField(related_name='shared', to=settings.AUTH_USER_MODEL),
        ),
    ]
